# Travis CI configuration for libseccomp-golang

# https://docs.travis-ci.com/user/reference/bionic
# https://wiki.ubuntu.com/Releases

dist: bionic
sudo: false

notifications:
  email:
    on_success: always
    on_failure: always

arch:
  - amd64

os:
  - linux

language: go

addons:
  apt:
    packages:
      - build-essential
      - astyle
      - golint
      - gperf

install:
  - go get -u golang.org/x/lint/golint

# run all of the tests independently, fail if any of the tests error
script:
  - wget https://github.com/seccomp/libseccomp/releases/download/v2.5.0/libseccomp-2.5.0.tar.gz
  - echo 463b688bf7d227325b5a465b6bdc3ec4 libseccomp-2.5.0.tar.gz | md5sum -c
  - tar xf libseccomp-2.5.0.tar.gz
  - pushd libseccomp-2.5.0 && ./configure && make && sudo make install && popd
  - make check-syntax
  - make lint
  - make check
